language: c

before_install:
 - wget "http://download.mono-project.com/archive/2.10.12/macos-10-x86/MonoFramework-MDK-2.10.12.macos10.xamarin.x86.dmg"
 - hdid "MonoFramework-MDK-2.10.12.macos10.xamarin.x86.dmg"
 - sudo installer -pkg "/Volumes/Mono Framework MDK 2.10.12/MonoFramework-MDK-2.10.12.macos10.xamarin.x86.pkg" -target /	
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  #- sudo apt-get update -qq > /dev/null
  #- sudo apt-get install -qq mono-devel > /dev/null

script:
  - xbuild src/threescale.NET.sln